### ISSUE TITLE
Parser doesn't support the & syntax

### ISSUE THREAD

**Issue by phated** [creditkarma/thrift-parser-fork#11]
I'm not sure what this is and need to do more research on it.

**Comment by phated** [comment]
I think this is a syntax for pointers but I can't find any documentation about it.  It seems to be used when a struct is defined with a type that has yet-to-be-declared but that struct will point to the first struct, causing recursion.  It also can be used to reference using the struct as a field property of itself.

Do we need these for JS?

**Comment by nnance** [comment]
No we don't need this.  We can backlog it or just remove it.

**Comment by phated** [comment]
I'll close it here and open it on the upstream repository.
