### ISSUE TITLE
Parser doesn't support dot-separated namespaces

### ISSUE THREAD

**Issue by phated** [creditkarma/thrift-parser-fork#14]
The `namespace` keyword seems to accept anything you give it, even though https://thrift.apache.org/docs/idl#namespace defines it to be one-of from a list.

**Comment by phated** [comment]
This seems to warn (in strict and non-strict mode) if the namespace doesn't have a generator or if the generator doesn't accept the sub-namespace.

**Comment by phated** [comment]
^ I think that would be the job of the compiler though, not the parser.  Thoughts?

**Comment by nnance** [comment]
well it would be the job of the code generator / compiler to parse / manage the namespace.  the parser should just provide it / manage it as a string

**Comment by phated** [comment]
Fixed by #60
