### ISSUE TITLE
Do we want to support xsd_all syntax?

### ISSUE THREAD

**Issue by phated** [creditkarma/thrift-parser-fork#30]
There seems to be a special `xsd_all` keyword for `union` and `struct` but the Thrift docs state:
> N.B.: The `xsd_all` keyword has some purpose internal to Facebook but serves no purpose in Thrift itself. Use of this feature is strongly discouraged.

Should we support this keyword? /cc @nnance

**Comment by nnance** [comment]
No.  We don't need this support for our use case and based on the docs I suggest we exclude support for it
