### ISSUE TITLE
Warnings

### ISSUE THREAD

**Issue by phated** [creditkarma/thrift-parser-fork#32]
Should we log warnings similar to the thrift binary?

**Comment by nnance** [comment]
Great feedback. Yes let's do it

**Comment by phated** [comment]
The upstream maintainer has decided that the parser should not do any logging and is instead making the error objects more robust.  I think this is a better solution overall so closing this.

**Comment by phated** [comment]
Ref https://github.com/eleme/thrift-parser/pull/13
