### ISSUE TITLE
Should the parser include the "option" for unions?

### ISSUE THREAD

**Issue by phated** [creditkarma/thrift-parser-fork#44]
While submitting some of my changes upstream, the maintainer said he would rather include all the information available on the AST (see https://github.com/eleme/thrift-parser/pull/6#discussion_r113278627).  This would mean our compiler would need to know to throw away the `option` property on Union types (I think this makes it a little more complex).

Should we follow the guidance by the upstream maintainer to get the changes upstreamed?

**Comment by phated** [comment]
Another recommendation by a community member on the upstream PR is to force each "option" property to "optional".

**Comment by nnance** [comment]
So what's your opinion.  To me if the thrift binary considers it invalid syntax we shouldn't support it but on the other hand we would have to manage our own fork which doesn't seem productive.

**Comment by phated** [comment]
The upstream maintainer hasn't responded to my followup questions.  I think it might be best to make the changes as he requested and push the invalid syntax checks into the compiler (the thrift binary has the luxury of handling all parts of the process so they can error wherever they like).

I'll create a PR for the changes as suggested by the upstream maintainer.

**Comment by phated** [comment]
Merged into develop.
