### ISSUE TITLE
Parser rounds numeric values greater than JS can handle

### ISSUE THREAD

**Issue by phated** [creditkarma/thrift-parser-fork#5]
I'm assuming this is because it is just constructing new numbers without determining their size.

**Comment by phated** [comment]
The parser doesn't operate on the values as numbers (though the compiler would), so maybe they can just be returned as string values.

With that solution, it would need to be determined if hex/e-notation numbers would be expanded as though they were numbers (would be more complicated that letting JS coerce).

**Comment by phated** [comment]
Maybe all numbers should be wrapped in an instance of `node-int64`?  @nnance thoughts?

**Comment by phated** [comment]
This might be best to just keep the numbers as strings during the parsing phase.

**Comment by nnance** [comment]
Let's just keep it as a string during parsing
