### ISSUE TITLE
Type check assignment of default field values

### ISSUE THREAD

**Issue by kevinbgreene** [creditkarma/thrift-parser-fork#64]
Related to #62 
We need to type check field assignments and throw errors on type mismatch. My first thought is the cleanest way to do this may be to alter the AST for values to be a complex type (a value field and a type field).

**Comment by phated** [comment]
@kevinbgreene I think this belongs in the `thrift-typescript` project.  Do you agree?

**Comment by kevinbgreene** [comment]
@phated I would usually expect type checking to happen as part of the parsing phase. I think the division of labor between the two libraries is cleaner if the parser produces a valid AST. To me thrift-typescript should be able to assume it gets a valid AST and it can just worry about code gen.

To me the reason I may want to put that logic in thrift-typescript is the fact we own that project and will be easier for us contribute to on our schedule.

It's probably not a pressing concern either way.

@nnance @ian-harshman-ck thoughts?

**Comment by phated** [comment]
I believe the upstream author has the opposite philosophy (the parser should be lax and the codegen should have validation/normalization).  If memory serves, he pushed back against forcing the "optional" flag for unions for that reason.

**Comment by kevinbgreene** [comment]
@phated Interesting... well, that would be that then. Well, if we are going to do that we should just remove those tests you were skipping and set up a validation phase in thrift-typescript. I'll move this issue over there.

If we're going to do a validation phase we could probably rewrite the AST to an intermediate form that would simplify code gen.

**Comment by kevinbgreene** [comment]
Moved to https://github.com/creditkarma/thrift-typescript/issues/53
